### ISSUE TITLE
Implementar Template Method

### ISSUE THREAD

**Issue by Numseinemmeunome** [gustavoreino/padroes-de-projeto#2]
Necessita-se implementar Template Method em BehavioralPatterns/.

**Comment by lucasmarcao** [comment]
Atribua para mim, por favor
EU IMPLORO !!!!

**Comment by lucasmarcao** [comment]
Implementei patrão 🙏🙏🙏🙌 !!!!

**Comment by Numseinemmeunome** [comment]
Fico perfeito chefe👌
