### ISSUE TITLE
Implementar exemplo para Design Pattern "Strategy"

### ISSUE THREAD

**Issue by atenokida** [gustavoreino/padroes-de-projeto#4]
## Description
Implemente um exemplo prático para o Design Pattern Strategy no repositório.

_"Strategy é um padrão de design comportamental que permite definir uma família de algoritmos, colocar cada um deles em uma classe separada e tornar seus objetos intercambiáveis."_ via [refactoring.guru](https://refactoring.guru/design-patterns/strategy).

## Tasks

- [x] Implementar exemplo dentro do seu diretório específico ("Strategy"  -> `BehavioralPatterns/`)
- [x] Adicionar arquivo `README.md` (ou `.txt`) contendo uma breve descrição e explicação do exemplo implementado.

**Comment by gustavoreino** [comment]
Atribua para mim, por favor
