### ISSUE TITLE
 Implementar exemplo para Design Pattern "Visitor"

### ISSUE THREAD

**Issue by gustavoreino** [gustavoreino/padroes-de-projeto#5]
## Description

Implemente um exemplo prático para o Design Pattern Visitor no repositório.

"Visitor é um padrão de design comportamental que permite separar algoritmos dos objetos nos quais eles operam." via [refactoring.guru](https://refactoring.guru/design-patterns/visitor).

## Tasks

- [x] Implementar exemplo dentro do seu diretório específico ("Visitor" -> BehavioralPatterns/)
- [x] Adicionar arquivo README.md (ou .txt) contendo uma breve descrição e explicação do exemplo implementado.

**Comment by atenokida** [comment]
Atribua para mim por favor
